import './styles.css';

export type Column = 'backlog' | 'doing' | 'done';
export interface Card { id:string; title:string; body:string; column:Column; labels:string[]; updatedAt:number; revision?:string }
export interface Conflict { cardId:string; local:string; remote:string; base:string; parentRevisionIds?:string[]; localCard?:Card; remoteCard?:Card }
export interface BackendCard { id:string; title:string; body:string; column:string; labels?:string[]; updated_at?:string; revision?:string }
export interface BackendEvent { path:string; kind:string; valid:boolean; duplicate:boolean; error?:string }
export interface BoardInfo { path:string; board_id:string; cards:string[] }
export const state = { boardPath:null as string|null, boardId:'', cards:[] as Card[], selected:null as string|null, conflicts:[] as Conflict[], connected:false, peer:'No devices paired', peerId:'', peerAddress:'', endpointId:'', endpointAddress:'', connection:'offline', error:'', loading:false };
const app = document.querySelector<HTMLDivElement>('#app') ?? (()=>{const el=document.createElement('div');el.id='app';document.body.append(el);return el;})();
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type InvokeFn = <T>(command:string,args?:Record<string,unknown>)=>Promise<T>;
let invokeImpl:InvokeFn|null=null;
async function invoke<T>(command:string,args?:Record<string,unknown>):Promise<T>{ if(invokeImpl)return invokeImpl<T>(command,args); const api=await import('@tauri-apps/api/core'); return api.invoke<T>(command,args); }
/** Test seam for exercising command failures and returned backend state. */
export function setInvokeForTests(fn:InvokeFn|null){invokeImpl=fn;}
type DirectoryPicker = (create:boolean)=>Promise<string|null>;
let directoryPickerForTests:DirectoryPicker|null=null;
export function setDirectoryPickerForTests(fn:DirectoryPicker|null){directoryPickerForTests=fn;}
async function chooseBoardDirectory(create:boolean):Promise<string|null>{
  if(directoryPickerForTests)return directoryPickerForTests(create);
  try{
    const {open}=await import('@tauri-apps/plugin-dialog');
    const selected=await open({directory:true,multiple:false,title:create?'Choose or create a board folder':'Open an IrohMD board folder'});
    return typeof selected==='string'?selected:null;
  }catch{
    return prompt(create?'New board folder path':'Board folder path');
  }
}
function normalize(x:BackendCard):Card{return {id:x.id,title:x.title,body:x.body,column:(['backlog','doing','done'].includes(x.column)?x.column:'backlog') as Column,labels:x.labels||[],updatedAt:x.updated_at?Date.parse(x.updated_at):Date.now(),revision:x.revision};}
function message(e:unknown){return e instanceof Error?e.message:String(e);}
function applyBoardInfo(info:BoardInfo){if(!info.board_id)throw new Error('Backend did not return a stable board ID');state.boardPath=info.path;state.boardId=info.board_id;}
async function loadCards(){if(!state.boardPath)return; state.loading=true; render(); try{const result=await invoke<BackendCard[]>('list_cards',{path:state.boardPath}); state.cards=(result||[]).map(normalize); state.error='';}catch(e){state.error='Unable to load cards: '+message(e);}finally{state.loading=false;render();}}
async function loadSync(){try{const [s,endpoint,peers]=await Promise.all([invoke<{connected:boolean;trusted_peers:number;endpoint_id?:string;address?:string;connection:string}>('sync_status'),invoke<{endpoint_id:string;address:string}>('endpoint_info'),invoke<{peer_id:string;trusted:boolean}[]>('list_trusted_peers')]);state.connected=!!s.connected;state.connection=s.connection;state.endpointId=endpoint.endpoint_id||s.endpoint_id||'';state.endpointAddress=endpoint.address||s.address||'';const trusted=peers.filter(x=>x.trusted);state.peer=trusted.map(x=>x.peer_id).join(', ')||'No devices paired';if(!state.peerId&&trusted.length)state.peerId=trusted[0].peer_id;}catch(e){state.error='Unable to read sync status: '+message(e);}render();}
function endpointIdFromAddress(address:string):string{const parsed=JSON.parse(address) as {id?:string};if(!parsed.id||typeof parsed.id!=='string')throw new Error('Endpoint address does not contain an id');return parsed.id;}
async function pairAddress(address:string){if(!state.boardPath||!state.boardId)throw new Error('Open a board with a stable board ID before pairing');const peerId=endpointIdFromAddress(address);const peer=await invoke<{peer_id:string;trusted:boolean}>('pair_peer_address',{peerId,address,authorizedBoards:[state.boardId]});if(!peer.trusted)throw new Error('Peer was not trusted');state.peerId=peer.peer_id;state.peerAddress=address;await loadSync();return peer;}
async function syncNow(){if(!state.boardPath||!state.boardId){state.error='Open a board with a stable board ID before syncing.';render();return}if(!state.peerId||!state.peerAddress){state.error='Pair a peer address before syncing.';render();return}state.loading=true;render();try{const result=await invoke<{status:string;transferred:number;received:number}>('sync_board',{path:state.boardPath,peerId:state.peerId,address:state.peerAddress});const successfulRoute=['connected','direct','relay'].includes(result.status);state.error=successfulRoute?'':`Sync finished with status: ${result.status}`;await loadCards();await loadSync();if(successfulRoute){state.connected=true;state.connection=result.status;state.error='';render();}}catch(e){state.error='Sync failed: '+message(e);state.loading=false;render();}}
async function openBoard(create=false){const p=await chooseBoardDirectory(create);if(!p)return;state.loading=true;state.error='';render();try{const command=create?'create_board':'open_board';const info=await invoke<BoardInfo>(command,{path:p});applyBoardInfo(info);await invoke('watch_board',{path:state.boardPath});await loadCards();await loadSync();}catch(e){state.error=(create?'Unable to create board: ':'Unable to open board: ')+message(e);state.boardPath=null;state.boardId='';state.cards=[];state.loading=false;render();}}
async function add(column:Column){if(!state.boardPath){state.error='Open or create a board before adding cards.';render();return}try{const saved=await invoke<BackendCard>('add_card',{path:state.boardPath,input:{title:'New card',body:'Add a description…',column,labels:[],position:1000}});state.cards.push(normalize(saved));state.selected=saved.id;state.error='';render();}catch(e){state.error='Unable to add card: '+message(e);render();}}
async function save(c:Card){if(!state.boardPath)return;const input={title:(document.querySelector<HTMLInputElement>('#title')!).value,body:(document.querySelector<HTMLTextAreaElement>('#body')!).value,column:(document.querySelector<HTMLSelectElement>('#column')!).value,labels:(document.querySelector<HTMLInputElement>('#labels')!).value.split(',').map(x=>x.trim()).filter(Boolean),position:1000};try{const saved=await invoke<BackendCard>('update_card',{path:state.boardPath,id:c.id,input});state.cards=state.cards.map(x=>x.id===c.id?normalize(saved):x);state.selected=null;state.error='';render();}catch(e){state.error='Unable to save card: '+message(e);render();}}
async function remove(id:string){if(!state.boardPath||!confirm('Delete this card?'))return;try{await invoke<boolean>('delete_card',{path:state.boardPath,id});state.cards=state.cards.filter(x=>x.id!==id);state.selected=null;state.error='';render();}catch(e){state.error='Unable to delete card: '+message(e);render();}}
async function move(id:string,column:Column){if(!state.boardPath)return;const old=state.cards.find(x=>x.id===id);if(!old)return;try{const saved=await invoke<BackendCard>('move_card',{path:state.boardPath,id,column,position:1000});state.cards=state.cards.map(x=>x.id===id?normalize(saved):x);render();}catch(e){state.error='Unable to move card: '+message(e);render();}}
async function resolveConflict(choice:string){const x=state.conflicts[0];if(!x||!state.boardPath)return;const c=x.localCard||state.cards.find(v=>v.id===x.cardId);if(!c||!x.parentRevisionIds||x.parentRevisionIds.length<2){state.error='Conflict resolution needs two parent revision IDs.';render();return}const payload={title:c.title,body:c.body,column:c.column,labels:c.labels,position:1000};try{const saved=await invoke<BackendCard>('resolve_conflict',{path:state.boardPath,id:x.cardId,resolution:{choice,local:payload,remote:payload,manual:choice==='manual'?payload:null,parentRevisionIds:x.parentRevisionIds}});state.cards=state.cards.map(v=>v.id===x.cardId?normalize(saved):v);state.conflicts=[];state.error='';render();}catch(e){state.error='Conflict resolution failed: '+message(e);render();}}
async function poll(){if(!state.boardPath)return;try{const events=await invoke<BackendEvent[]>('poll_watch_events');if(events.length){const bad=events.find(x=>!x.valid&&x.error);if(bad)state.error=bad.error!;const conflict=events.find(x=>x.error?.toLowerCase().includes('conflict'));if(conflict){const id=conflict.path.split('/').pop()?.replace(/\.md$/,'')||'unknown';const local=state.cards.find(c=>c.id===id);state.conflicts=[{cardId:id,local:local?JSON.stringify(local,null,2):'Local version unavailable',remote:conflict.error||'Remote version payload unavailable',base:'Base version unavailable',localCard:local,parentRevisionIds:local?.revision?[local.revision]:[]}];}await loadCards();}}catch(e){state.error='Unable to poll board changes: '+message(e);render();}}
function editor(c:Card){return '<div class="modal-backdrop"><section class="editor" role="dialog" aria-modal="true" aria-labelledby="edit-title"><div class="editor-head"><span id="edit-title">EDIT CARD</span><button class="close" id="close" aria-label="Close">×</button></div><input id="title" value="'+esc(c.title)+'" aria-label="Title"/><textarea id="body" aria-label="Description">'+esc(c.body)+'</textarea><label>Column<select id="column"><option '+(c.column==='backlog'?'selected':'')+' value="backlog">Backlog</option><option '+(c.column==='doing'?'selected':'')+' value="doing">In progress</option><option '+(c.column==='done'?'selected':'')+' value="done">Done</option></select></label><label>Labels<input id="labels" value="'+esc(c.labels.join(', '))+'" aria-label="Labels"/></label><div class="editor-actions"><button class="danger" id="delete">Delete card</button><button class="primary" id="save">Save changes</button></div></section></div>';}
function conflictModal(x:Conflict){const ready=(x.parentRevisionIds?.length||0)>=2;return '<div class="modal-backdrop"><section class="conflict" role="dialog" aria-modal="true"><div class="editor-head"><span>CONFLICT DETECTED</span></div><h2>Conflict requires review</h2><p>'+esc(x.remote)+'</p>'+(!ready?'<p class="error">Resolution awaits two parent revision IDs from the backend.</p>':'')+'<div class="editor-actions"><button data-resolve="local" '+(ready?'':'disabled')+'>Keep local</button><button data-resolve="remote" '+(ready?'':'disabled')+'>Keep remote</button><button data-resolve="manual" '+(ready?'':'disabled')+'>Manual merge</button></div></section></div>';}
function render(){const cols:[Column,string,string][]=[['backlog','Backlog','Ideas and upcoming work'],['doing','In progress','Currently being worked on'],['done','Done','Shipped and complete']];app.innerHTML='<header><div class="brand"><span class="mark">✦</span><div><strong>IROHMD</strong><small>MARKDOWN KANBAN</small></div></div><div class="board-name">'+(state.boardPath?esc(state.boardPath):'Untitled board')+'</div><div class="header-actions"><button class="ghost" id="copy-endpoint" title="Copy local endpoint address">Copy endpoint</button><button class="ghost" id="pair">⌘ Pair device</button><span class="status '+(state.connected?'online':'offline')+'" role="status"><i></i>'+ (state.connected?'Synced':'Offline')+'</span></div></header><main><aside><button class="primary wide" id="new-card">＋ New card</button><nav><button class="nav active">▦ Board</button></nav><div class="side-section"><label>WORKSPACE</label><button class="side-item" id="open">▣ Open board</button><button class="side-item" id="create">＋ Create board</button></div><div class="side-bottom"><div class="sync-card"><div class="sync-title">Sync status</div><p>'+(state.connected?'Connected to '+esc(state.peer):esc(state.connection)+' · '+esc(state.peer))+'</p><p class="endpoint"><strong>Local endpoint</strong><code title="'+esc(state.endpointAddress)+'">'+(state.endpointAddress?esc(state.endpointAddress):'Starting…')+'</code></p><button class="link" id="sync">↻ Sync board</button></div></div></aside><section class="workspace"><div class="toolbar"><div><h1>My board</h1><p>'+state.cards.length+' cards · changes saved to Markdown</p></div></div>'+(state.loading?'<p class="notice">Loading…</p>':'')+(state.error?'<p class="error" role="alert">'+esc(state.error)+'</p>':'')+'<div class="columns">'+cols.map(([id,name,hint])=>'<section class="column" data-column="'+id+'"><div class="column-head"><div><h2>'+name+' <b>'+state.cards.filter(x=>x.column===id).length+'</b></h2><small>'+hint+'</small></div><button class="add" data-add="'+id+'" aria-label="Add card to '+name+'">＋</button></div><div class="dropzone">'+state.cards.filter(x=>x.column===id).map(c=>'<article class="card '+(state.selected===c.id?'selected':'')+'" draggable="true" data-id="'+c.id+'"><div class="card-top"><span class="drag">⠿</span><button class="more" data-delete="'+c.id+'" aria-label="Delete '+esc(c.title)+'">···</button></div><h3>'+esc(c.title)+'</h3><p>'+esc(c.body)+'</p><div class="card-foot">'+c.labels.map(l=>'<span class="tag">'+esc(l)+'</span>').join('')+'</div></article>').join('')+'<button class="drop-add" data-add="'+id+'">＋ Add card</button></div></section>').join('')+'</div></section></main>'+(state.selected?editor(state.cards.find(c=>c.id===state.selected)!):'')+(state.conflicts.length?conflictModal(state.conflicts[0]):'');bind();}
function bind(){document.querySelector('#new-card')?.addEventListener('click',()=>add('backlog'));document.querySelectorAll<HTMLElement>('[data-add]').forEach(x=>x.addEventListener('click',()=>add(x.dataset.add as Column)));document.querySelector('#open')?.addEventListener('click',()=>openBoard());document.querySelector('#create')?.addEventListener('click',()=>openBoard(true));document.querySelector('#copy-endpoint')?.addEventListener('click',async()=>{if(!state.endpointAddress){state.error='Local endpoint address is not ready.';render();return}try{await navigator.clipboard.writeText(state.endpointAddress);state.error='';}catch(e){state.error='Unable to copy endpoint: '+message(e);}render();});document.querySelector('#pair')?.addEventListener('click',async()=>{const address=prompt('Paste the full serialized EndpointAddr');if(!address)return;try{await pairAddress(address);state.error='';render();}catch(e){state.error='Pairing failed: '+message(e);render();}});document.querySelector('#sync')?.addEventListener('click',syncNow);document.querySelector('#close')?.addEventListener('click',()=>{state.selected=null;render();});document.querySelector('#save')?.addEventListener('click',()=>{const c=state.cards.find(x=>x.id===state.selected);if(c)save(c)});document.querySelector('#delete')?.addEventListener('click',()=>{if(state.selected)remove(state.selected)});document.querySelectorAll<HTMLElement>('.card').forEach(el=>{el.addEventListener('click',e=>{if(!(e.target as HTMLElement).dataset.delete){state.selected=el.dataset.id!;render();}});el.addEventListener('dragstart',e=>(e as DragEvent).dataTransfer?.setData('text/plain',el.dataset.id!));});document.querySelectorAll<HTMLElement>('.column').forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{const id=(e as DragEvent).dataTransfer?.getData('text/plain');if(id)move(id,el.dataset.column as Column);});});document.querySelectorAll<HTMLElement>('[data-delete]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();remove(x.dataset.delete!)}));document.querySelectorAll<HTMLElement>('[data-resolve]').forEach(x=>x.addEventListener('click',()=>resolveConflict(x.dataset.resolve!)));}
render();setInterval(poll,2000);loadSync();
export { normalize, applyBoardInfo, loadCards, loadSync, pairAddress, syncNow, poll, openBoard, chooseBoardDirectory };
